class HomeConstants{
  List<String> doctorSectionsNames = [
    "الكل",
    "الاسنان",
    "اطفال",
    "نسائية",
    "جراحة عامة",
    "باطنية",
    "جلدية",
    "تجميل",
    "انف اذن حنجرة",
    "عيون",
    "عظام",
    "اعصاب",
    "قلبية",
    "جهاز هضمي",
    "بولية",
    "اورام",
    "امراض دم",
    "نفسية",
  ];
  List<String> doctorSectionsImages = [
    "assets/sections/all.png",
    "assets/sections/dentist.png",
    "assets/sections/children.png",
    "assets/sections/women.png",
    "assets/sections/surgery.png",
    "assets/sections/abdomen.png",
    "assets/sections/skin.png",
    "assets/sections/beauty.png",
    "assets/sections/ear-nose.png",
    "assets/sections/eyes.png",
    "assets/sections/bones.png",
    "assets/sections/nerves.png",
    "assets/sections/heart.png",
    "assets/sections/digestive.png",
    "assets/sections/urinary.png",
    "assets/sections/tumors.png",
    "assets/sections/blood.png",
    "assets/sections/sycho.png",
  ];
  List<String> doctorProfessions = [
    "اختصاص عام",
    "طبيب الاسنان",
    "طبيب اطفال",
    "طبيب نسائية",
    "طبيب جراح",
    "طبيب باطنية",
    "طبيب جلدية",
    "طبيب تجميل",
    "انف اذن حنجرة",
    "طبيب العيون",
    "طبيب عظام",
    "طبيب اعصاب",
    "طبيب قلبية",
    "طبيب جهاز هضمي",
    "طبيب بولية",
    "طبيب اورام",
    "طبيب امراض دم",
    "طبيب نفسي",
  ];

  List<String> offerSectionsNames = [
    "الكل",
    "الاسنان",
    "ليزر",
    "جلدية",
    "تجميل",
    "شعر",
    "تحاليل",
    "رشاقة",
  ];
  List<String> offerSectionsImages = [
    "assets/sections/all.png",
    "assets/sections/dentist.png",
    "assets/sections/laser.png",
    "assets/sections/skin2.png",
    "assets/sections/beauty2.png",
    "assets/sections/hair.png",
    "assets/sections/analysis.png",
    "assets/sections/fitness.png"
  ];
  List<String> offerProfessions = [
    "جميع الاختصاصات",
    "طب الاسنان",
    "اختصاص ليزر",
    "اختصاص الجلدية",
    "طب تجميلي",
    "عناية الشعر",
    "تحاليل",
    "رشاقة",
  ];

  List<String> branches = [
    "العروض",
    "المراكز",
    "الصيدليات",
    "الاطباء",
  ];
  List<String> provinces = [
    "الكل",
    "بغداد",
    "أربيل",
    "الأنبار",
    "بابل",
    "البصرة",
    "حلبجة",
    "دهوك",
    "القادسية",
    "ديالى",
    "ذي قار",
    "السليمانية",
    "صلاح الدين",
    "كركوك",
    "كربلاء",
    "المثنى",
    "ميسان",
    "النجف",
    "نينوى",
    "واسط",
  ];
}